language: python 
python:
  - "3.6"

services: 
  - postgresql
  - redis-server

addons:
  postgresql: "9.4"
  firefox: "latest"

env:
  matrix:
    - DJANGO=2.1 DB=postgres
  global:
    - SECRET_KEY=not_so_secret
      B_DATABASE_URL="postgres://postgres@localhost/test_db"
      ALLOWED_HOSTS= "localhost"
      SENTRY_DSN=""
      REDIS_URL="redis://localhost:6379"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - xvfb-run make test
  - python manage.py test --settings=floodrelief.test_settings
