language: python 
python:
  - "3.6"

services: 
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
  firefox: "latest"

env:
  matrix:
    - DJANGO=2.1 DB=postgres
  global:
    - SECRET_KEY=not_so_secret
      B_DATABASE_URL="postgres://postgres@localhost/test_db"
      ALLOWED_HOSTS= "localhost"
      INTERNAL_IPS= "localhost"
      SENTRY_DSN=""
      REDIS_URL="redis://localhost:6379"

before_install:
  - version=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | python -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")
  - url=$(echo https://github.com/mozilla/geckodriver/releases/download/$version/geckodriver-$version-linux64.tar.gz)
  - mkdir geckodriver
  - curl -sL $url | tar -xz -C geckodriver
  - export PATH=$PWD/geckodriver:$PATH

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - python manage.py test --settings=floodrelief.test_settings
